spring.application.name=ecommerce-webapp
server.port=8484
spring.web.resources.static-locations=classpath:/static/,classpath:/staticcopy/
server.shutdown=graceful
spring.mvc.problemdetails.enabled=true

######## BookStore Application Configuration ########
ecommerce.api-gateway-url=http://localhost:8989

######## Actuator Configuration ########
management.endpoints.web.exposure.include=*


